// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzkCXHxg930qZrC6A4_DOKXg1trJ0_NE',
    appId: '1:288684786570:web:f607ce0c1971a5208d7e73',
    messagingSenderId: '288684786570',
    projectId: 'booking-app-sweden',
    authDomain: 'booking-app-sweden.firebaseapp.com',
    storageBucket: 'booking-app-sweden.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2y4kiQHEwAXy-Hogwwqzx-9XhvIpQ434',
    appId: '1:288684786570:android:0d937ae028c4e8ba8d7e73',
    messagingSenderId: '288684786570',
    projectId: 'booking-app-sweden',
    storageBucket: 'booking-app-sweden.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZS6a25nzoDLuLOiy44tb80VSfzn05tE8',
    appId: '1:288684786570:ios:e666b802c3b5f0198d7e73',
    messagingSenderId: '288684786570',
    projectId: 'booking-app-sweden',
    storageBucket: 'booking-app-sweden.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZS6a25nzoDLuLOiy44tb80VSfzn05tE8',
    appId: '1:288684786570:ios:ac4165ef434090b18d7e73',
    messagingSenderId: '288684786570',
    projectId: 'booking-app-sweden',
    storageBucket: 'booking-app-sweden.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
